headersOrigin = "config"
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\Lenovo\\OneDrive - MBK Group\\Documents\\Visual\\public\\deploy\\prj001-lumpini24"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\Lenovo\\OneDrive - MBK Group\\Documents\\Visual\\public\\deploy\\prj001-lumpini24"
command = "echo 'Static site - no build needed'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/medias/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/client/images/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/project/images/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/sw.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"